### PR TITLE
Block Google from collecting data

### PR DESCRIPTION
**Pull request by vanowm**
Block Google from collecting javascript errors and other data

Might need more tests. So far I see no issues.

### CODE REVIEW

**Comment by OrangeDrangon** [comment]
This is a change I am willing to make if it we are certain that there are no negative side effects. Sounds like you are still unsure at this time.

**Comment by vanowm** [comment]
Yeah. let's wait a bit more, I've been running it for 3 days and so far see nothing wrong with it. Just a bunch of "blocked" request messages in the console.

**Comment by qwertym0nk** [comment]
@OrangeDrangon @vanowm It has been a few months now, has testing been completed and can this finally be merged?

**Comment by vanowm** [comment]
@qwertym0nk  I've been using this in my own build since than and had no side effects or problems. Everything works fine.

**Comment by OrangeDrangon** [comment]
I will merge this then release a version this weekend.

**Pull request merged**
