### PR TITLE
Message count in tray

### PR DESCRIPTION
**Pull request by vanowm**

### CODE REVIEW

**Comment by vanowm** [comment]
I found a way add an overlay badge to an icon, with ability change the size and position related to the icon itself.
There are three caveats though: on windows it looks quiet bad when using .ico file as base icon, so .png images used instead. Second, the icon generator is using `canvas` which is not available in trayManager.ts, so it generates icon in bridge.ts, than passes to `trayManager.setUnreadIcon()`.
Lastly, not sure if it works on macOS since it uses icon template instead.
Will try another pull request later.

**Comment by vanowm** [comment]
Accidentally this also fixes #226 and #229 (making  #227, #228 and #237 obsolete)

On Windows system there seems to be a [bug](https://github.com/electron/electron/issues/27321) in Electron, which prevents changing icon on a window that has "attention" state enabled (aka highlighted taskbar button)
I was not able find a work around this issue.

**Comment by OrangeDrangon** [comment]
Thanks so much for the hard work squashing bugs in your numerous pull requests. This specific change is  not going to be merged at this time. I find the numbers too hard to read on small icons. Thanks again for all the great work.

**Comment by vanowm** [comment]
Have you tried increase badge size? It might be monitor related though, cause on my 27" and 19"  monitors with 1440p, and 1200p resolution I can clearly see all the numbers, maybe 5 and 6 at first hard to distinguish, also size 25% makes it look almost the same as the default unread icon with a dot.

**Pull request closed without merging**
