### PR TITLE
upgrade electron

### PR DESCRIPTION
**Pull request by ElementalWarrior**
I couldn't get the application to run unless I unset contextIsolation.
So here is the application split into preload and node files.

Makes iterop a bit more painful. But everything seems to work, at least
as far as I tested. I think the interop stuff makes error logging a bit
painful, so I may have missed the mark a bit. I can say for certain that
clicking notifications works as expected. The mutation observer stuff
I'm a little less clear on. (But the functions are called when I used
console.log statements).

I completely removed the profileImage stuff, it doesn't appear to be
necessary. Maybe its just Linux, but the notification rendered the
NotificationsOptions.icon that was provided by the google SPA just
fine without all the cache code.

### CODE REVIEW

**Comment by ElementalWarrior** [comment]
Oh yeah, I only tested on Linux (Sway window manager). So other linux testers and Mac + windows is welcome.

**Comment by LanikSJ** [comment]
Thanks for the heads up I'll try this on a Mac and I'll let you know how it works.

**Comment by OrangeDrangon** [comment]
:eyes:

Thanks for the contribution. I will look this over tonight. I have tried and failed to upgrade the version a few times. I did not know about this new way of doing things.

**Comment by ElementalWarrior** [comment]
> Thanks for the contribution. I will look this over tonight. I have tried and failed to upgrade the version a few times. I did not know about this new way of doing things.

Yeah for the life of me I could not figure out why it didn't just work with `contextIsolation: false`.

They have some docs talking about context isolation, and related is sandboxing:
- https://www.electronjs.org/docs/latest/tutorial/context-isolation
- https://www.electronjs.org/docs/latest/tutorial/sandbox

Nothing I found points to context isolation being deprecated, so I'm really not sure why all this was necessary. I would have expected it to work the same. :shrug:

**Comment by ElementalWarrior** [comment]
Thanks for merging my PR :)

**Pull request merged**
