### PR TITLE
Set user agent of the webcontents before loading the html

### LINKED ISSUE #157: Google Fi Integration
Issue:
Google Fi was recently integrated into Android Messages instead of using Hangouts as the default messaging app.  The Messages app provides a link to sign in with your email address, but then I get an error that I am not using a supported browser.  I can use the old way of signing in with the QR code, but then I lose the extra features that I would get with using my Google Fi account.

Solution:
Enable signing in with my Google Fi account.  Not sure what it would take to become a "supported browser" within the app?

Alternatives:
None that I can think of.

Screenshot:
image
image
image

### PR DESCRIPTION
**Pull request by OrangeDrangon**
A lot of experimentation will be needed here. I hope we can get this working.

Closes #157

### CODE REVIEW

**Comment by numbernegative** [comment]
Tested and just setting the user agent still triggered the unsecured browser block.
Adding a webrequest for the Google Accounts URL did work.
The Fi functionality is now allowing login and it seems to be working perfectly as intended.

```
    // set user agent to potentially make google fi work
	
	mainWindow.webContents.session.webRequest.onBeforeSendHeaders(
        {
            urls: ['https://accounts.google.com/*'],
        },
        (details, callback) => {
            const newRequestHeaders = Object.assign(
                {},
                details.requestHeaders || {},
                {
                    'User-Agent':
                        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0',
                }
            )
            callback({ requestHeaders: newRequestHeaders })
        }
    )
```

**Comment by OrangeDrangon** [comment]
Is this in addition to the previous commit or does it replace it?

**Comment by numbernegative** [comment]
Replace the previous. The commit you just made looks right.

**Comment by OrangeDrangon** [comment]
Well let me know if it works for you and if it does I will merge it.

**Comment by numbernegative** [comment]
Will do when off work in a few hours.

**Review by OrangeDrangon — COMMENTED** [review]
Comment for posterity:

Potential bug not fully passing the details object to the callback. I do not know enough if that is even correct behavior but if we have more problems it could be that.

**Comment by numbernegative** [comment]
Looks good. Even recognized I'm already signed in and loaded straight to the Fi page without needing to do anything.

**Comment by hawkeyetwolf** [comment]
In case others run into this: After not using my computer for a while, I had to remove the account from the Android Messages app login, then re-login for it to "allow the browser".

**Pull request merged**
