### PR TITLE
User-Agent Fix for OrangeDrangon/android-messages-desktop#441

### PR DESCRIPTION
**Pull request by drislands**
Modified how the user agent is set when sending headers. There were two issues that I was able to identify.

First, the Google sign-in page sends requests to the youtube.com domain sometimes, so the existing replacement effect was not always firing. Adding a url entry for this domain fixes this problem.

Second, Google sometimes doesn't like the hard-coded user agent this project was previously providing. I have no idea why -- this Electron/user agent/Google problem has been ongoing for years. I've solved this problem this time by instead taking the user agent Electron would have passed by itself and stripping out only the Electron-specific component.

I don't know how long this fix will last, since Google seems intent on being opaque about how they determine if a browser is secure or not. Fingers crossed.

### CODE REVIEW

**Comment by OrangeDrangon** [comment]
@drislands thanks for the patch will get it released once the checks finish

**Comment by drislands** [comment]
@OrangeDrangon Thank you! Glad I was able to help.

**Comment by drislands** [comment]
@OrangeDrangon I just saw one of the checks failed with an "already_exists" error code -- is this something I should have seen and fixed before the PR? I'm not sure what the solution is but I'll do whatever it needs to make it work.

**Comment by OrangeDrangon** [comment]
No that was a problem with the ci pipeline.

Thanks
Kyle

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=a3lsZUBla3Jvc2VuYmVyZy5jb20=>

**Pull request merged**
